### ISSUE TITLE
Skip already normalized files

### ISSUE THREAD

**Issue by hschult** [loosolab/jlu-bda-2020#44]
It would be nice if the pipeline would check if a file already was normalized and skip it if it was. At the moment it seems like it just overwrites and normalizes everything again.

**Comment by kmlr81** [comment]
This one is a bit complicated. It is partially done already. The log-normalised files are saved seperately and each file is only log-scaled once (if the corresponding log-scaled file is already there the process is not gone through again). But the min-max-scaling is always done in relation to the current files in the run, so those values will not work for a run with different files.

**Comment by hschult** [comment]
Ah ok, my bad. Would it then be possible to know the min and max used for scaling? Then you could skip if it would be the same limits.

**Comment by msbentsen** [comment]
Maybe this is more of a general question, but if you are anyway always scaling the values to the current max... why not just always scale the values to e.g. 100?

What is the gain from calculating the new max every time?

**Comment by kmlr81** [comment]
The new max serves as a boundary upward. The highest value is scaled to 1 and the lowest to 0 and all other values are scaled in between according to their distance to the highest and lowest values. This assures that the values are distributed between the borders of 0 and 1 in a way that makes sense for each analysis run. If I would use a fixed max value that would not work. Either the value would need to be high, like 100, which in turn would cause significantly smaller values to crowd near zero, recreating the same problem we had due to outliers before. Or there might be values in the data set bigger than the fixed max and that would result in values greater than 1. 
At least, if I am thinking correctly.
So it makes more sense to determine the min and max values individually for each run.

As to the other part of the question: Was the explanation given during the Friday meeting sufficient so that I can close the issue, or are there still further questions?
